# Generated by Django 4.0.2 on 2023-05-24 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productmodel_category_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='master_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='master', to='products.categorymodel'),
            preserve_default=False,
        ),
    ]
