# Generated by Django 4.0.2 on 2023-05-24 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_categorymodel_master_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='master_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master', to='products.categorymodel'),
        ),
    ]
